// generated by the @nuxtjs/tailwindcss <https://github.com/nuxt-modules/tailwindcss> module at 3/17/2026, 5:00:04 PM
import "@nuxtjs/tailwindcss/config-ctx"
import configMerger from "@nuxtjs/tailwindcss/merger";

import cfg2 from "./../../tailwind.config.ts";
const config = [
{"content":{"files":["/Users/waqr/Desktop/trial-sim/app/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/waqr/Desktop/trial-sim/app/components/global/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/waqr/Desktop/trial-sim/app/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/waqr/Desktop/trial-sim/app/layouts/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/waqr/Desktop/trial-sim/app/plugins/**/*.{js,ts,mjs}","/Users/waqr/Desktop/trial-sim/app/composables/**/*.{js,ts,mjs}","/Users/waqr/Desktop/trial-sim/app/utils/**/*.{js,ts,mjs}","/Users/waqr/Desktop/trial-sim/app/pages/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/waqr/Desktop/trial-sim/app/{A,a}pp.{vue,js,jsx,mjs,ts,tsx}","/Users/waqr/Desktop/trial-sim/app/{E,e}rror.{vue,js,jsx,mjs,ts,tsx}","/Users/waqr/Desktop/trial-sim/app/app.config.{js,ts,mjs}","/Users/waqr/Desktop/trial-sim/app/spa-loading-template.html"]}},
{},
cfg2
].reduce((acc, curr) => configMerger(acc, curr), {});

const resolvedConfig = config;

export default resolvedConfig;